site_name: Database Systems Project
site_url: https://example.com/docs/
theme:
    name: material
    palette:
        primary: white
    features:
        - content.code.copy
        - content.tabs.link

extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - attr_list
    - md_in_html
    - pymdownx.highlight:
          anchor_linenums: true
          linenums: true
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: pymdownx.superfences.fence_code_format

nav:
    - Home: index.md
    - 1. Node.js Setup: nodejs-setup.md
    - 2. Sync vs Async Code: sync-vs-async-nodejs.md
    - 3. JavaScript Basics: javascript-basics.md
    - 4. Functions: functions.md
    - 5. Promises: callbacks-promises-async-await.md
    - 6. Express.js Basics: expressjs-basics.md
    - 7. Req & Res: nodejs-request-response.md
    - 8. Middlewares: nodejs-middlewares.md
    - 9. Project Structure: project-structure.md
    - 10. Routes & Modules: routes-import-export.md
    - 11. PostgreSQL Connectivity: postgresql-connectivity.md
    - 12. REST API: rest-api-get-post.md
    - 13. API Clients: rest-api-client.md
    - 14. Alpine.js CRUD: alpinejs-crud-app.md
    - 15. Final Project: final-project.md
    # - 16. Table: table.md
